services:
  api:
    build: .
    container_name: image-spoofing-api
    ports:
      - "8001:8001"
    volumes:
      # Mount file .env lokal ke dalam container
      - ./.env:/app/.env
      # Cache model agar tidak download ulang jika ganti container
      - model_cache:/root/.cache
    environment:
      - MODEL_PATH=models/2.7_80x80_MiniFASNetV2.pth
    restart: unless-stopped

volumes:
  model_cache: 