version: '3.8'

services:
  api:
    build: .
    container_name: image-spoofing-api
    ports:
      - "8001:8001"
    volumes:
      # Mount .env file
      - ./.env:/app/.env
      # Persist Model Cache (OpenCLIP/Torch) to avoid re-downloading
      - model_cache:/root/.cache
    environment:
      - MODEL_PATH=models/2.7_80x80_MiniFASNetV2.pth
    restart: unless-stopped

volumes:
  model_cache:
